# -*- coding: utf-8 -*-
"""Sqlprojectvisualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bt5JY5EzFtNeMeW-295TJ-L207pJ91rO
"""

import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

df=pd.read_csv("Amazon.csv")

df.head(10)

df.columns

df['Date'] = pd.to_datetime(df['Date'])

df["Sales"] = df["Unit price"] * df["Quantity"]

df.head(1)

daily_sales = df.groupby('Date')['Sales'].sum()

plt.figure(figsize=(10, 6))
sns.lineplot(x=daily_sales.index, y=daily_sales.values, marker='o')
plt.title('Daily Sales Trend')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.show()

df.columns

Average_order_value=df.groupby("Customer type")["Sales"].mean().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(x="Customer type",y="Sales",data=Average_order_value)
plt.title("Average Order Value by Customer Type")
plt.xlabel("Customer Type")
plt.ylabel("Average Order Value")
plt.show()

average_quantity_purchased = df.groupby("Customer type")["Quantity"].mean().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(x="Customer type",y="Quantity",data=average_quantity_purchased)
plt.title("Average Quantity purchased by Customer Type")
plt.xlabel("Customer Type")
plt.ylabel("Average quantity purchased")
plt.show()

product_popularity = df.groupby('Product line')['Quantity'].sum().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(x="Product line",y="Quantity",data=product_popularity)
plt.title("Product Popularity")
plt.xlabel("Product Line")
plt.ylabel("Quantity")
plt.show()

daily_sales = df.groupby('Date')['Sales'].sum().reset_index()

plt.figure(figsize=(10,6))
sns.lineplot(x="Date",y="Sales",data=daily_sales, marker ="o")
plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

gender_sales = df.groupby('Gender')['Sales'].sum().reset_index()

plt.figure(figsize=(10,6))
sns.barplot(x="Gender",y="Sales",data=gender_sales)
plt.title("Sales by Gender")
plt.xlabel("Gender")
plt.ylabel("Sales")
plt.show()

customer_gender=df.groupby("Customer type")["Gender"].value_counts().reset_index(name="Count")

# Create a cross-tabulation (contingency table)
customer_gender_table = pd.crosstab(df['Customer type'], df['Gender'])

# Create the heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(customer_gender_table, annot=True, fmt="d", cmap="YlGnBu")
plt.title('Customer Type vs. Gender')
plt.xlabel('Gender')
plt.ylabel('Customer Type')
plt.show()

quantity_sales = df.groupby('Quantity')['Sales'].sum().reset_index()

plt.figure(figsize=(10,6))
sns.lineplot(x="Quantity",y="Sales",data=quantity_sales, marker="o")
plt.title("Quantity vs Sales")
plt.xlabel("Quantity")
plt.ylabel("Sales")
plt.show()

